FILM = [
    {   
        id: '1',
        name: 'Lật mặt 6',
        year: '2023',
        director : 'Lý Hải',
        main_charactor : 'Lý Hải, Quốc Cường, Trung Dũng, Huy Khánh, Thanh Thức, Trần Kim Hải, Huỳnh Thi, Diệp Bảo Ngọc, Tú Tri, Quỳnh Như, Tạ Lâm, bé Thùy Linh…',
        describe : 'Lật mặt 6: Tấm vé định mệnh" thuộc thể loại tâm lý, giật gân (thriller), khác với dòng hành động của các phim trước đó trong series. Lý Hải phục dựng một làng nghề làm chiếu đang có nguy cơ thất truyền giữa bối cảnh ở miền Tây',
        time: '100 phút',
        rating : '7/10' ,
        src : 'https://www.youtube.com/embed/1ZSytvp2I0I',
        type_film : 'chiếu rạp',
        pic : 'lat-mat-6-poster.jpg'
    } ,
    {   
        id: '2',
        name: 'Nhà Bà Nữ',
        year: '2023',
        director : 'Trấn Thành',
        main_charactor : 'Lê Dương Bảo Lâm, Song Luân, Lê Giang, Khả Như, Trấn Thành, NSND Ngọc Giàu',
        describe : 'Nhà bà Nữ là một bộ phim điện ảnh chính kịch, gia đình của Việt Nam năm 2023 do Trấn Thành sản xuất kiêm đạo diễn. Bộ phim do Đỗ Hoàng Vũ, quản lý của Trấn Thành và Hari Won đảm nhận vai trò đồng sản xuất. Đây là bộ phim thứ hai do Trấn Thành làm đạo diễn sau Bố già, bộ phim có doanh thu cao thứ hai lịch sử phòng vé Việt Nam sau khi bị Nhà bà Nữ vượt mặt.',
        time: '102 phút',
        rating : '6.4/10' ,
        src : 'https://www.youtube.com/embed/pg4L29p98Kw',
        type_film : 'chiếu rạp',
        pic : 'nha-ba-nu-poster.jpg'
    } ,
    {   
        id: '3',
        name: 'Mất tích',
        year: '2023',
        director : 'Nick Johnson, Will Merrick',
        main_charactor : 'Storm Reid, Nia Long, Joaquim de Almeida, Tim Griffin, Daniel Henney, Amy Landecker',
        describe : 'Mất Tích là bộ phim từ những người từng tạo ra SEARCHING đã trở lại với MISSING ! “Missing” bắt đầu khi Grace (Nia Long) cùng bạn trai Kevin Lin (Ken Leung) đi du lịch Colombia. Sau vài ngày không liên lạc, cô con gái Ali (Storm Reid) bàng hoàng nhận ra mẹ mình đã mất tích một cách bí ẩn. Hết cách, Ali đành phải cố đăng nhập vào các tài khoản liên lạc hay mạng xã hội của mẹ để tìm manh mối. Cô dần khám phá ra những bí mật đen tối mà Grace che giấu suốt bấy lấu. Hàng loạt câu hỏi ập xuống đầu cô gái trẻ. Những mối quan hệ xã hội của Grace là ai? Thân phận thật sự của Kevin là gì? Liệu gã có phải tội phạm và lên kế hoạch bắt cóc Grace?',
        time: '111 phút',
        rating : '7.2/10' ,
        src : 'https://www.youtube.com/embed/seBixtcx19E',
        type_film : 'chiếu rạp',
        pic: 'mat-tich-poster.jpg'
    } ,
    {   
        id: '4',
        name: 'Phi vụ toàn sao',
        year: '2023',
        director : 'Guy Ritchie',
        main_charactor : 'Jason Statham, Aubrey Plaza, Cary Elwes, Hugh Grant, Josh Hartnett, Bugzy Malone',
        describe : 'Phi Vụ Toàn Sao kể về đặc vụ Orson Fortune và nhóm đặc vụ của anh ta tuyển dụng một trong những ngôi sao điện ảnh lớn nhất của Hollywood để giúp họ thực hiện một nhiệm vụ bí mật khi việc bán một công nghệ vũ khí mới chết người có nguy cơ phá vỡ trật tự thế giới.',
        time: '115 phút',
        rating : '6.4/10' ,
        src : 'https://www.youtube.com/embed/WdZ-BWWQcWQ',
        type_film : 'chiếu rạp',
        pic: 'phi-vu-toan-sao-poster.jpg'
    } ,
    {   
        id: '5',
        name: 'Đàm phán',
        year: '2023',
        director : 'Im Soon Rye',
        main_charactor : 'Hwang Jung Min, Hyun Bin, Kang Ki Young, Lee Chun Moo, Jung Jae Sung, Lee Seung Chul',
        describe : 'Đàm Phán kể về một nhà ngoại giao Hàn Quốc được cử đến Afghanistan khi một nhóm du khách Hàn Quốc bị Taliban bắt làm con tin. Khi mọi biện pháp đều thất bại và một con tin bị giết, anh ta buộc phải hợp tác với một đặc vụ để giải cứu những người sống sót.',
        time: '108 phút',
        rating : '6.1/10' ,
        src : 'https://www.youtube.com/embed/MCjFhsp6gO4',
        type_film : 'chiếu rạp',
        pic: 'dam-phan-poster.jpg'
    } ,
    {   
        id: '6',
        name: 'Shazam! Cơn thịnh nộ của thần linh',
        year: '2023',
        director : 'David F. Sandberg',
        main_charactor : 'Zachary Levi, Asher Angle, Jack Dylan Grazer',
        describe : 'Bộ phim tiếp tục câu chuyện về cậu thiếu niên Billy Batson, khi đọc thuộc lòng từ ma thuật "SHAZAM!" được biến thành Siêu anh hùng thay thế bản ngã trưởng thành của anh ấy, Shazam.',
        time: '130 phút',
        rating : '6.6/10' ,
        src : 'https://www.youtube.com/embed/l37LjoV9W7M',
        type_film : 'chiếu rạp',
        pic: 'shazam-con-thinh-no-cua-than-linh-poster.jpg'
    } ,
    {   
        id: '7',
        name: 'Vong hồn rước lễ',
        year: '2023',
        director : 'Victor Garcia',
        main_charactor : 'Carla Campra, Aina Quinones, Marc Soler',
        describe : 'Tháng 5 năm 1987. Trở về từ một hộp đêm và sau khi dùng thuốc, cô gái mới đến thị trấn Sara và bạn của cô ấy là Rebe tìm thấy một con búp bê mặc lễ phục. Kể từ giây phút đó, cuộc sống của họ sẽ trở thành địa ngục trần gian.',
        time: '98 phút',
        rating : '5.9/10' ,
        src : 'https://www.youtube.com/embed/_JrZflM5OSI',
        type_film : 'chiếu rạp',
        pic: 'vong-hon-ruoc-le-poster.jpg'
    } ,
    {   
        id: '8',
        name: 'Siêu lừa gặp siêu lầy',
        year: '2023',
        director : 'Võ Thanh Hòa',
        main_charactor : 'Mạc Văn Khoa, Anh Tú, Mỹ Duyên, Nhất Trung',
        describe : 'Thuộc phong cách hành động – hài hước với các “cú lừa” thông minh và lầy lội đến từ bộ đôi Tú (Anh Tú) và Khoa (Mạc Văn Khoa), Siêu Lừa Gặp Siêu Lầy của đạo diễn Võ Thanh Hòa theo chân của Khoa – tên lừa đảo tầm cỡ “quốc nội” đến đảo ngọc Phú Quốc với mong muốn đổi đời.',
        time: '135 phút',
        rating : '6.0/10' ,
        src : 'https://www.youtube.com/embed/ecNMIlP7wIs',
        type_film : 'chiếu rạp',
        pic: 'sieu-lua-gap-sieu-lay-poster.jpg'
    } ,
    {   
        id: '9',
        name: 'Tìm nhà cho Boss',
        year: '2022',
        director : 'Joo-hwan Kim',
        main_charactor : 'Tea-Hyun Cha, Joeng Ji-Hoon, Hyoen-ji Park',
        describe : 'Tìm nhà cho boss" kể về một người đàn ông sắp kết hôn trải qua một chuyến phiêu lưu, khi cùng người bạn của mình lên đường đưa chú chó của cậu đến những người trông giữ thú cưng.',
        time: '114 phút',
        rating : '7.6/10' ,
        src : 'https://www.youtube.com/embed/sRi4jXUX8Rk',
        type_film : 'chiếu rạp',
        pic: 'tim-nha-cho-boss-poster.jpg'
    } ,
    {   
        id: '10',
        name: 'Đêm tối rực rỡ',
        year: '2022',
        director : 'Aaron Toronto',
        main_charactor : 'Huỳnh Kiến An, Phương Dung, Nhã Uyên',
        describe : 'Trong ánh đèn rực rỡ và tiếng nhạc ồn ào thường thấy đám tang tiễn đưa người thân sẽ là nơi bạn có thể biết được nhiều điều về gia đình đó. Và đám tang trong phim đã khắc họa chi tiết khi các bi kịch của một gia đình đồng loạt bị phanh phui.',
        time: '103 phút',
        rating : '7.9/10' ,
        src : 'https://www.youtube.com/embed/tgL4qAcLy4Y',
        type_film : 'chiếu rạp',
        pic : 'dem-toi-ruc-ro-poster.jpg'
    } ,
    {   
        id: '11',
        name: 'Mọi thứ mọi nơi mọi lúc',
        year: '2022',
        director : 'Dan Kwan, Daniel Scheinert',
        main_charactor : 'Dương Tử Quỳnh, Quan Kế Huy, Stephanie Hsu',
        describe : 'Mọi Thứ Mọi Nơi Mọi Lúc kể về một người nhập cư Trung Quốc già nua bị cuốn vào một cuộc phiêu lưu điên cuồng, nơi cô ấy một mình có thể cứu thế giới bằng cách khám phá các vũ trụ khác kết nối với cuộc sống mà cô ấy có thể đã dẫn dắt.',
        time: '139 phút',
        rating : '7.9/10' ,
        src : 'https://www.youtube.com/embed/wxN1T1uxQ2g',
        type_film : 'chiếu rạp',
        pic :'cuoc-chien-da-vu-tru-poster.jpg'
    } ,
    {   
        id: '12',
        name: 'Avatar 2: Dòng chảy của nước',
        year: '2022',
        director : 'James Cameron',
        main_charactor : 'Sam Worthington, Zoe Saldana, Dương Tử Quỳnh',
        describe : 'Thế Thân: Dòng Chảy Của Nước lấy bối cảnh 10 năm sau những sự kiện xảy ra ở phần đầu tiên. Phim kể câu chuyện về gia đình mới của Jake Sully (Sam Worthington thủ vai) cùng những rắc rối theo sau và bi kịch họ phải chịu đựng khi phe loài người xâm lược hành tinh Pandora.',
        time: '192 phút',
        rating : '7.8/10' ,
        src : 'https://www.youtube.com/embed/NZrX_ES93JA',
        type_film : 'chiếu rạp',
        pic: 'avatar-2-poster.jpg'
    } ,
    {   
        id: '13',
        name: 'Black Adam',
        year: '2022',
        director : 'Jaume Collet-Serra',
        main_charactor : 'Dwayne Johnson, Sarah Shahi, Pierce Brosnan, Noah Centineo, Aldis Hodge, Joseph Gatt, Natalie Burn, Quintessa Swindell',
        describe : 'Black Adam là câu chuyện gần 5.000 năm sau khi anh ta được ban cho sức mạnh toàn năng của các vị thần Ai Cập - và bị cầm tù nhanh chóng - Black Adam được giải thoát khỏi ngôi mộ trần gian của mình, sẵn sàng giải phóng hình thức công lý độc nhất của anh ta trên thế giới hiện đại.',
        time: '125 phút',
        rating : '6.3/10' ,
        src : 'https://www.youtube.com/embed/X0tOpBuYasI',
        type_film : 'chiếu rạp',
        pic :'black-adam-poster.jpg'
    } ,
    {   
        id: '14',
        name: 'Sát thủ nhân tạo 2',
        year: '2022',
        director : 'Park Hoon Jung',
        main_charactor : 'Shin Shi Ah, Jo Min Soo, Park Eun Bin, Seo Eun Soo, Jin Goo, Sung Yoo Bin',
        describe : 'Sát Thủ Nhân Tạo 2: Mẫu Vật Còn Lại là câu chuyện lợi dụng sự cố kinh hoàng tại cơ sở thí nghiệm, cô nàng 17 tuổi mang bí danh ARK-ADP1, một nữ sát thủ nhân tạo có siêu năng lực, đã thoát được ra ngoài. Cô bị những người tạo ra mình lẫn các thế lực bí ẩn khác truy bắt gắt gao.',
        time: '138 phút',
        rating : '6.2/10' ,
        src : 'https://www.youtube.com/embed/EgOiCWTR_JU',
        type_film : 'chiếu rạp',
        pic : 'sat-thu-nhan-tao-poster.jpg'
    } ,
    {   
        id: '15',
        name: 'Godzilla đại chiến Kong',
        year: '2021',
        director : 'Adam Wingard',
        main_charactor : 'Alexander Skarsgard, Millie Bobby Brown, Kyle Chandler, Rebecca Hall, Brian Tyree Henry',
        describe : 'Godzilla đại chiến Kong là câu chuyện sau các sự kiện diễn ra ở “Godzilla: King of the Monsters”, trong thời đại mà các Titans đòi lại quyền làm chủ hành tinh, cuộc đấu tranh sinh tồn giữa loài người với chúng đã dẫn đến một cuộc chiến không thể tránh khỏi giữa Godzilla và Kong.',
        time: '113 phút',
        rating : '6.3/10' ,
        src : 'https://www.youtube.com/embed/odM92ap8_c0',
        type_film : 'chiếu rạp',
        pic : 'godzilla-dai-chien-cong.jpg'
    } ,
    {   
        id: '16',
        name: 'Siêu trộm',
        year: '2021',
        director : 'Jaume Balagueró',
        main_charactor : 'Famke Janssen, Freddie Highmore, Astrid Bergès-Frisbey',
        describe : 'Siêu Trộm trong "Money Heist phiên bản điện ảnh" SIÊU TRỘM, Thom (Freddie Highmore) và đồng đội của mình sẽ đột nhập vào ngân hàng Tây Ban Nha - một nơi bí ẩn bậc nhất thế giới, để khám phá chiếc két sắt trăm tuổi nằm dưới lòng đất.',
        time: '118 phút',
        rating : '6.4/10' ,
        src : 'https://www.youtube.com/embed/L41IJiageyg',
        type_film : 'chiếu rạp',
        pic: 'sieu-trom-poster.jpg'
    } ,
    {   
        id: '17',
        name: 'Khóa cửa chặt nào Suzume',
        year: '2023',
        director : 'Makoto Shinkai',
        main_charactor : 'Nanoka Hara, Hokuto Matsumura, Eri Fukatsu',
        describe : 'Một câu chuyện phiêu lưu hành động hiện đại nơi một cô gái 17 tuổi tên Suzume giúp một chàng trai trẻ bí ẩn đóng những cánh cửa từ bên ngoài đang gây ra thảm họa trên khắp Nhật Bản. ',
        time: '122 phút',
        rating : '7.8/10' ,
        src : 'https://www.youtube.com/embed/5pTcio2hTSw',
        type_film : 'Phim hoạt hình',
        pic: 'khoa-cua-chat-nao-suzume-poster.jpg'
    } ,
    {   
        id: '18',
        name: 'One Piece Film: Red',
        year: '2023',
        director : 'Goro Taniguchi',
        main_charactor : 'Mayumi Tanaka, Kazuya Kuroiwa, Eiichiro Oda',
        describe : 'Lần đầu tiên, Uta - ca sĩ được yêu thích nhất trên thế giới - sẽ tiết lộ bản thân với cả thế giới tại một buổi hòa nhạc trực tiếp. Giọng hát mà cả thế giới chờ đợi sắp vang lên. ',
        time: '115 phút',
        rating : '6.7/10' ,
        src : 'https://www.youtube.com/embed/89JWRYEIG-s',
        type_film : 'Phim hoạt hình',
        pic : 'one-piece-film-red-poster.jpg'
    } ,
    {   
        id: '19',
        name: 'Minions: Sự trỗi dậy của Gru',
        year: '2022',
        director : 'Kyle Balda, Brad Ableson, Jonathan del Val ',
        main_charactor : 'Steve Carell, Lucy Lawless, Michelle Yeoh',
        describe : 'Minions: Sự Trỗi Dậy Của Gru là câu chuyện rất lâu trước khi trở thành một phản diện chuyên nghiệp, Gru chỉ là một cậu bé 12 tuổi sống ở vùng ngoại ô vào những năm 1970, với ước mơ một ngày sẽ làm “bá chủ” thế giới. Và 3 “quả chuối” vàng biết đi từ trên trời rơi xuống đã là những đồng đội đầu tiên của Gru, bên cạnh ủng hộ cậu bé, cùng nhau thiết kế những vũ khí đầu tiên, thực hiện những phi vụ đầu tiên.',
        time: '88 phút',
        rating : '6.5/10' ,
        src : 'https://www.youtube.com/embed/6DxjJzmYsXo',
        type_film : 'Phim hoạt hình',
        pic : 'minions-su-troi-day-cua-gru-poster.jpg'
    } ,
    {   
        id: '20',
        name: 'Tom & Jerry: quậy tung New York',
        year: '2021',
        director : 'Tim Story',
        main_charactor : 'Chloë Grace Moretz, Michael Peña, Colin Jost ',
        describe : 'Một trận chiến hỗn loạn xảy ra giữa chuột Jerry, người đã trú ẩn trong khách sạn Royal Gate, và Tom Cat, người được thuê để đuổi anh ta đi trước ngày đám cưới lớn đến.',
        time: '101 phút',
        rating : '5.2/10' ,
        src : 'https://www.youtube.com/embed/kP9TfCWaQT4',
        type_film : 'Phim hoạt hình',
        pic : 'tom-&-jerry-quay-tung-new-york-poster.jpg'
    } ,
    {   
        id: '21',
        name: 'Chuột nhí và sứ mệnh thần biển',
        year: '2023',
        director : 'David Alaux, Eric Tosti, Jean-François Tosti',
        main_charactor : 'Kaycie Chase, Christophe Lemoine, Emmanuel Curtil',
        describe : 'Cuộc sống ở Yolcos, một thành phố cảng xinh đẹp và thịnh vượng ở Hy Lạp cổ đại, yên bình cho đến khi dân số bị đe dọa bởi cơn thịnh nộ của Poseidon. Một con chuột trẻ tuổi, thích phiêu lưu và con mèo đã nhận nuôi cô giúp đỡ Jason già và Argonauts của anh ta trong hành trình giải cứu thành phố.',
        time: '95 phút',
        rating : '6.5/10' ,
        src : 'https://www.youtube.com/embed/BH0rkCQjTfI',
        type_film : 'Phim hoạt hình',
        pic : 'chuot-nhi-va-su-menh-than-bien-poster.jpg'
    } ,
    {   
        id: '22',
        name: 'Mèo đi hia',
        year: '2022',
        director : 'Joel Crawford, Januel Mercado',
        main_charactor : 'Antonio Banderas, Salma Hayek, Harvey Guillén',
        describe : 'Khi Puss in Boots phát hiện ra rằng niềm đam mê phiêu lưu của mình đã bị ảnh hưởng và nó đã đốt cháy tám trong số chín mạng sống của mình, nó bắt đầu một cuộc hành trình hoành tráng để khôi phục chúng bằng cách tìm ra Điều ước cuối cùng thần thoại.',
        time: '102 phút',
        rating : '7.9/10' ,
        src : 'https://www.youtube.com/embed/Y5zqweZAEKI',
        type_film : 'Phim hoạt hình',
        pic : 'meo-di-hia-poster.jpg'
    } ,
    {   
        id: '23',
        name: 'Thanh Gươm Diệt Quỷ 3: Đường đến làng rèn gươm',
        year: '2023',
        director : 'Haruo Sotozaki',
        main_charactor : 'Zach Aguilar, Laila Berzins, Kira Buckland',
        describe : 'Tất cả các Quỷ cấp cao tập hợp tại Lâu đài Vô cực sau thất bại của Lục quỷ cấp cao.',
        time: '110 phút',
        rating : '6.5/10' ,
        src : 'https://www.youtube.com/embed/Fy2Gr7t-yWI',
        type_film : 'Phim hoạt hình',
        pic : 'thanh-guom-diet-quy-3-poster.jpg'
    } ,
    {   
        id: '24',
        name: 'Doraemon: Stand By Me 2',
        year: '2022',
        director : 'Ryuichi Yagi, Takashi Yamazaki',
        main_charactor : 'Bakarhythm, Shihoko Hagino, Shinichi Hatori',
        describe : 'Doraemon: Đôi Bạn Thân 2 kể về một ngày nọ, Nobita khi này đã trưởng thành tìm thấy một con gấu nhồi bông do người bà yêu quý của mình làm. Cậu không thể ngừng suy nghĩ về những kỷ niệm tuổi thơ của mình nên đã cầu xin Doraemon sử dụng cỗ máy thời gian để qua trở lại quá khứ',
        time: '96 phút',
        rating : '7.5/10' ,
        src : 'https://www.youtube.com/embed/A0wg3Zkxq1c',
        type_film : 'Phim hoạt hình',
        pic : 'doraemon-stand-by-me-2-poster.jpg'
    } ,
    {   
        id: '25',
        name: 'Doraemon: Nobita và cuộc chiến vũ trụ tí hon',
        year: '2022',
        director : 'Yamaguchi Susumu',
        main_charactor : 'Subaru Kimura, Megumi Oohara, Megumi Oohara, Kakazu Yumi, Seki Tomokazu',
        describe : 'Nobita tình cờ gặp được người ngoài hành tinh tí hon Papi, vốn là Tổng thống của hành tinh Pirika, chạy trốn tới Trái Đất để thoát khỏi những kẻ nổi loạn nơi quê nhà. Doraemon, Nobita và hội bạn thân dùng bảo bối đèn pin thu nhỏ biến đổi theo kích cỡ giống Papi để chơi cùng cậu bé. Thế nhưng, một tàu chiến không gian tấn công cả nhóm. Cảm thấy có trách nhiệm vì liên lụy mọi người, Papi quyết định một mình đương đầu với quân phiến loạn tàn ác. Doraemon và các bạn lên đường đến hành tinh Pirika, sát cánh bên người bạn của mình.',
        time: '109 phút',
        rating : '6.5/10' ,
        src : 'https://www.youtube.com/embed/HiJagWy2mEI',
        type_film : 'Phim hoạt hình',
        pic : 'doraemon-nobita-va-cuoc-chien-vu-tru-ti-hon-poster.jpg'
    } ,
    {   
        id: '26',
        name: 'Jujutsu Kaisen 0: Chú thuật hồi chiến',
        year: '2021',
        director : 'Seong-Hu Park',
        main_charactor : 'Chinatsu Akasaki, Aya Endô, Kana Hanazawa',
        describe : 'Yuta Okkotsu, một học sinh trung học giành được quyền kiểm soát một Linh hồn bị nguyền rủa cực kỳ mạnh mẽ và được các Phù thủy Jujutsu đăng ký vào trường trung học Jujutsu của tỉnh Tokyo để giúp anh ta kiểm soát sức mạnh của mình và để mắt đến anh ta.',
        time: '112 phút',
        rating : '7.8/10' ,
        src : 'https://www.youtube.com/embed/UPRqnFnnrr8',
        type_film : 'Phim hoạt hình',
        pic : 'jujutsu-kaisen-0-poster.jpg'
    } ,
    {   
        id: '27',
        name: 'Belle: Rồng và công chúa tàn nhang',
        year: '2021',
        director : 'Mamoru Hosoda',
        main_charactor : 'Kaho Nakamura, Ryo Narita, Shôta Sometani',
        describe : 'Suzu là một học sinh trung học nhút nhát sống ở một ngôi làng nông thôn. Trong nhiều năm, cô chỉ là cái bóng của chính mình. Nhưng khi bước vào "U", một thế giới ảo rộng lớn, cô thoát ra khỏi nhân vật trực tuyến của mình với tư cách là Belle, một ca sĩ được yêu mến trên toàn cầu.',
        time: '121 phút',
        rating : '7.1/10' ,
        src : 'https://www.youtube.com/embed/izIycj3j4Ow',
        type_film : 'Phim hoạt hình',
        pic : 'belle-rong-va-cong-chua-tan-nhang-poster.jpg'
    } ,
    {   
        id: '28',
        name: 'Học viện anh hùng: Thế kỉ mới của anh hùng',
        year: '2019',
        director : 'Kenji Nagasaki',
        main_charactor : 'Daiki Yamashita, Nobuhiko Okamoto, Yuki Kaji',
        describe : 'Khi một giáo phái khủng bố hủy hoại một thành phố bằng cách giải phóng chất độc khiến khả năng của mọi người vượt khỏi tầm kiểm soát, những anh hùng vĩ đại nhất của Nhật Bản đã lan rộng khắp thế giới trong nỗ lực truy tìm kẻ chủ mưu và đưa hắn ra trước công lý.',
        time: '101 phút',
        rating : '7.1/10' ,
        src : 'https://www.youtube.com/embed/ZclBluzAZVE',
        type_film : 'Phim hoạt hình',
        pic : 'hoc-vien-anh-hun-poster.jpg'
    } ,
    {   
        id: '29',
        name: 'Lyle, Chú cá sấu biết hát',
        year: '2022',
        director : 'Josh Gordon, Will Speck ',
        main_charactor : 'Javier Barden, Winslow Fegley, Shawn Mendes',
        describe : 'Feature film based on the children s book about a crocodile that lives in New York City.',
        time: '106 phút',
        rating : '6.1/10' ,
        src : 'https://www.youtube.com/embed/s0W6O7mSlaU',
        type_film : 'Phim hoạt hình',
        pic : 'lyle-chu-ca-sau-biet-hat-poster.jpg'
    } ,
    {   
        id: '30',
        name: 'Khách sạn huyền bí: Ma cà rồng biến hình',
        year: '2022',
        director : 'Derek Drymon, Jennifer Kluska',
        main_charactor : 'Brian Hull, Andy Samberg, Selena Gomez, Kathryn Hahn, Keegan-Michael Key',
        describe : 'Tập phim cuối cùng của thương hiệu với màn hoán đổi thân phận hài hước gây náo loạn cả xứ sở quái vật. Cậu con rể của Dracula đã thành công trong việc tự biến thành quái vật. Thế nhưng, dù có là giống loài nào thì bản tính hậu đậu trời ban vẫn không thể rời xa Johnny.',
        time: '87 phút',
        rating : '6.0/10' ,
        src : 'https://www.youtube.com/embed/ldBroBrV6Fg',
        type_film : 'Phim hoạt hình',
        pic : 'khach-san-huyen-bi-ma-ca-rong-bien-hinh-poster.jpg'
    } ,
    {   
        id: '31',
        name: 'Đấu trường âm nhạc 2',
        year: '2021',
        director : 'Garth Jennings',
        main_charactor : 'Matthew Scarlett Johansson, Taron Egerton, Tori Kelly, Halsey, Pharrell Williams',
        describe : 'Đấu Trường Âm Nhạc 2 kể về sau khi thành công rực rỡ tại quê nhà, Buster Moon và các bạn quyết định dấn thân vào một cuộc chinh phục âm nhạc mới hoành tráng và cam go hơn bao giờ hết.',
        time: '110 phút',
        rating : '7.4/10' ,
        src : 'https://www.youtube.com/embed/EPZu5MA2uqI',
        type_film : 'Phim hoạt hình',
        pic : 'dau-truong-am-nhac-2-poster.jpg'
    } 

]


// alert(FILM[0]['name'])